### ISSUE TITLE
Poor performance on Linux

### ISSUE THREAD

**Issue by alexhultman** [jonashaag/bjoern#176] opened 2020-01-24 21:36 UTC
Hello,
I'm assembling some performance results and found that Bjoern is much faster on macOS than on Linux.

I get one eighth the performance on Linux benchmarking with wrk. Is this by design? Is macOS the preferred platform or is something wrong?

**Comment by jonashaag** [comment] 2020-01-25 08:46
Can you please share your exact benchmark setup on both machines?

**Comment by alexhultman** [comment] 2020-01-25 12:26
I just took any default MacBook from 2019 and ran wrk from Homebrew with default settings against python3 from Homebrew; performance was in the category of Japronto roughly.

Then I ran it on Clear Linux with their python3 and my compiled wrk (which I know to perform very well) with again default settings and yeah performance was one eighth (10k vs 84k).

It's usually the other way around, Linux should outperform macOS in networking

**Comment by jonashaag** [comment] 2020-01-25 18:01
Thanks! Can you please share the exact Python application you were serving and command line parameters, and also the wrk configuration. 

Can you also provide the max number of fds as reported by ulimit by your executing shell

**Comment by alexhultman** [comment] 2020-01-25 23:31
No different than the most simple hello world app, no configuration other than default wrk http://localhost:8080 no extra parameters in any way, just straight out default and minimal.

I have like a million fds because I run larger tests from time to time, but wrk only uses 10 for this

**Comment by jonashaag** [comment] 2020-01-26 08:23
Hm, just ran some benchmarks, it's looking ok, completely non-optimized Linux server w/ 2 vCPUs:

```py
import bjoern

def app(env,sr):
    sr('200 ok', [('content-length','0')])
    return ''

bjoern.run(app, 'localhost', 8888, reuse_port=1)
```

```
$ venv/wrk/wrk -t12 -c400 -d10s http://127.0.0.1:8888/index.html
Running 10s test @ http://127.0.0.1:8888/index.html
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.76ms    5.45ms 139.52ms   84.60%
    Req/Sec     3.93k     1.08k   19.63k    80.95%
  470512 requests in 10.09s, 27.82MB read
Requests/sec:  46628.11
Transfer/sec:      2.76MB
```

```
$ venv/wrk/wrk -t4 -c20 -d10s http://127.0.0.1:8888/index.html
Running 10s test @ http://127.0.0.1:8888/index.html
  4 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   557.60us    1.69ms  49.67ms   98.13%
    Req/Sec    12.09k     4.20k   24.55k    76.25%
  481385 requests in 10.03s, 28.46MB read
Requests/sec:  48016.14
Transfer/sec:      2.84MB
```

Same numbers with multiple workers (either fork or receive steering).

I'd be very curious to reproduce this in your environment!

**Comment by ar-qun** [comment] 2020-03-25 14:59
I heard Clear Linux is used by Intel specifically for development and might not be a the most representative.

**Comment by alexhultman-2fa** [comment] 2020-04-15 11:49
That makes no sense. Clear Linux is a performance dist, and my very first comment mentioned that I get very high numbers with other server software.

The point I'm making and the bug I'm reporting is that - Bjoern has very competitive performance on macOS compared to other server software, but on Linux the deviation between that very same server software and Bjoern is very much to disadvantage for Bjoern.

That is, I'm not reporting Bjoern is slow, it isn't, but on Linux it is strangely non-competitive as if something was wrong.

Because getting **one eighth** the performance on Linux, compared to other server software is very poor.

**Comment by ar-qun** [comment] 2020-04-15 12:02
> That makes no sense. Clear Linux is a performance dist, and my very first comment mentioned that I get very high numbers with other server software.

Unfortunately it might be due to a number of issues plus Clear Linux being an exotic distro, plus Jonas was not able to reproduce your findings in an other distros. It would be helpful if you could provide him a minimal reproducible example, which I think Jonas requested in his previous comment.

For example you could use https://hub.docker.com/_/clearlinux and try to replicated you setup in a container.

**Comment by alexhultman-2fa** [comment] 2020-04-16 05:51
I think Jonas did in fact replicate it. 48k for two CPUs - numbers mean nothing without info on what exactly those CPUs are, but it sounds way low.

**Comment by jonashaag** [comment] 2020-04-16 05:56
No I can’t reproduce and are looking for an example.

**Comment by alexhultman-2fa** [comment] 2020-05-31 07:23
Alright the difference is the most with default wrk settings:

```
./wrk http://localhost:3000
Running 10s test @ http://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.33ms   13.38ms  42.21ms   78.97%
    Req/Sec     6.02k     1.68k    9.64k    70.00%
  120611 requests in 10.07s, 10.81MB read
Requests/sec:  11982.66
Transfer/sec:      1.07MB
```

With 400 connections like you used the numbers are different:

```
./wrk -c400 http://localhost:3000
Running 10s test @ http://localhost:3000
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.05ms   14.71ms  45.77ms   78.16%
    Req/Sec    29.59k     4.64k   40.56k    70.00%
  588631 requests in 10.02s, 52.80MB read
Requests/sec:  58760.47
Transfer/sec:      5.27MB
```

But either way it doesn't come close to other python servers with similar goals, on Linux. Here running with default wrk settings:

```
./wrk http://localhost:3000
Running 10s test @ http://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    67.36us   41.30us   4.23ms   90.27%
    Req/Sec    74.29k     8.69k   98.37k    65.35%
  1493810 requests in 10.10s, 102.57MB read
Requests/sec: 147908.51
Transfer/sec:     10.16MB
```

Where the diff is more than 10x, going down to 2.5x with 400 connections. So the case I'm primarily reporting is the one where you run default wrk settings - that's where the diff is unreasonably large.

Here's the very basic example test:

```
import bjoern

# This simple test does not include routing
def application(env, start_response):
	start_response('200 OK', [])
	return b"Hello Python!"

# I get poor performance on Linux, much better on macOS?
# 10k ish on Linux, 84k on macOS, let's compare on macOS to make it even!
bjoern.run(application, "localhost", 3000)
```

All of these numbers are running on my 10+ year old laptop, with same Python version.

**Comment by jonashaag** [comment] 2020-05-31 09:31
Thanks, trying now in a Clear Linux Docker container. Can you please compare performance in your setup to Clear Linux running inside Docker, and to Ubuntu running inside Docker?

Also can you share what's the Python server in the last example, and the exact application code?

**Comment by jonashaag** [comment] 2020-06-11 07:50
It’s an apples to oranges comparison. Japronto isn’t a WSGI server. I’ll benchmark just for curiosity anyways :)

Btw I never got around to setting up Clear Linux since packages took forever to download and there’s no packaged libev. So that took too much time for my gusto. 

I’ll be closing this ticket but feel free to continue the discussion!

**Closed by jonashaag** 2020-06-11 07:50 UTC

**Comment by alexhultman-2fa** [comment] 2020-06-11 09:03
You're missing the point yet again; I'm **not** saying "Japronto is faster therefore bu huu" I'm saying that Bjoern **has** competitive performance **on macOS** (in the same realm as Japronto) this is a **compliment (I'm expressing positive feedback)**, but **on Linux** it has 10x lower perf.. compared to **the same Japronto**. The point I'm making from the start is that something is severely lower performing on Linux when it comes to Bjoern. That's the only point I've ever made. My point never was that Japronto equals Bjoern, I use Japronto as a verifiable example, showing the relative issue.

The entire idea with this report was to make it clear that I get overly poor results in benchmarks and that they don't align with the much better results I get on macOS - it was meant to give you heads up to check what is wrong.

If I wanted to be an asshole I would take the results I got on Linux (10x lower) and used those to misrepresent Bjoen, but **I didn't**. I used the results from macOS so that it better showed its potentials.
