### ISSUE TITLE
Refactor bjoern.py to a class

### ISSUE THREAD

**Issue by Gabriel-Gardin** [jonashaag/bjoern#216] opened 2021-07-12 19:50 UTC
I'm working on a POC where I need to use SSL, as it's not a real project it must remain simple, so I don't want to use NGINX as a reverse proxy with SSL termination.

Therefore, I would like to override the run method to wrap the socket with SSL. It would be cleaner to do that  if the functions under bjoern.py were refactor to use classes. 

I could do that and make a pull request if you agree.

Anyway, thanks for the great work!

**Comment by jonashaag** [comment] 2021-07-13 08:57
I'd consider this a duplicate of #143

**Closed by jonashaag** 2021-07-13 08:57 UTC
