### ISSUE TITLE
cpu 100% endless active loop on bjoern 1.4.2

### ISSUE THREAD

**Issue by dPeS** [jonashaag/bjoern#88] opened 2015-09-08 07:27 UTC
First of all - thanks for making this code - I find it really good approach to wsgi gateway.
I wanted to give it a shot on pre-production new kind of service that I've launched recently - it's low latency rest endpoint.

After some tests we find out that bjoern falls in active wait on epool (monitored with strace), but still handling requests right. I assume it's a bug because falling back to uwsgi solved this problem.

launched with reuse_port, like this:
bjoern.run(wsgi.application, 'localhost', 8000, reuse_port=True)

My question is what kind of input do You need to debug?

**Comment by jonashaag** [comment] 2015-09-08 15:08
Thanks for the report!

Which release are you using? Have you tried with the latest master? What OS and libev versions?

First, you could try to build bjoern with `make debug` and reproduce the bug. Please paste the output here.

Could you try reproducing the bug with some other WSGI application than the ones you originally used? (Something as simple as https://github.com/jonashaag/bjoern/blob/master/tests/listen.py) Could you try other HTTP clients to make the request, like a browser, curl, wget?

**Comment by dPeS** [comment] 2015-09-20 14:08
bjoern (1.4.2)
Ubuntu 14.04.3 LTS
libev4 1:4.15-3 or 4.15 probably

how to compile with debug? I will start with it first

**Comment by jonashaag** [comment] 2015-09-20 19:47
> how to compile with debug? I will start with it first

Download the repo from GitHub and type `make debug`.

**Comment by kianxineki** [comment] 2016-04-05 09:39
I have exactly the same problem:
bjoern==1.4.2
bottle==0.12.9
community/libev 4.20-1 [installed]

Linux archdroid 3.14.29-12-ARCH #1 SMP PREEMPT Fri Mar 25 18:48:58 MDT 2016 aarch64 GNU/Linux

**Comment by jonashaag** [comment] 2016-04-05 11:20
Thanks for the heads up! Could you check out bjoern master, compile it with `make debug`, and try that on your project? (You'll have to add the `build` folder to your PYTHONPATH, like so: `PYTHONPATH=build:. python myproject.py`)

**Comment by kianxineki** [comment] 2016-04-05 13:36
is correct?
```bash
git clone https://github.com/jonashaag/bjoern.git
cd bjoern
git clone https://github.com/nodejs/http-parser.git
make debug
python2 setup.py install
```
the failure of 100% cpu load is not immediate, usually fail the next day.

As the public has information here.

**Comment by kianxineki** [comment] 2016-04-05 13:41
upon receiving a request returns "Segmentation fault (core dumped)", I've compiled wrong?
```
Bottle v0.12.9 server starting up (using BjoernServer())...
Listening on http://0.0.0.0:9998/
Hit Ctrl-C to quit.

Segmentation fault (core dumped)
```

**Comment by jonashaag** [comment] 2016-04-05 14:27
You're using a wrong version of http-parser, please delete the directory and use `git submodule update --init`

**Comment by kianxineki** [comment] 2016-04-05 14:39
it's works !, fail as I leave the error here.

Thank you!

**Comment by kianxineki** [comment] 2016-04-05 14:56
It just happened, nothing appears in the debug

http://i.imgur.com/KblcsAa.png

**Comment by kianxineki** [comment] 2016-04-05 15:22
I reproduce the error.
I opened the url of the web.
I leave the F5 pressed for a few seconds.

Answers the requests but then left in infinite loop.

It may be that when you close the connection when the server is sending into an infinite loop?

**Comment by jonashaag** [comment] 2016-04-09 20:53
Hm, I still can't reproduce this. Which browser are you using? Could you post the output of the `dbg` branch I just created?

**Comment by kianxineki** [comment] 2016-04-10 00:16
@jonashaag chromium 48.0.2564.116 Built on 8.3, running on Debian 8.3 (64-bit)
I recorded a video playing error, I hope you serve to try to reproduce the error


https://www.youtube.com/watch?v=VVSssFiT1TE

**Comment by kianxineki** [comment] 2016-04-10 00:31
@jonashaag i tested branch "tmp"
It has generated a log of almost 800MB! when it is blocked not to print debug things.

I captured the output. What attachment in a message
[bjoern_log.zip](https://github.com/jonashaag/bjoern/files/211557/bjoern_log.zip)

**Comment by jonashaag** [comment] 2016-04-10 06:48
Oops, haha, thanks for testing it, I'll have a look tomorrow.

**Comment by jonashaag** [comment] 2016-04-10 06:52
From a quick look I would tell it's a bug I suspected yesterday when I had a look at the source code and tried to debug this in my head: After a successful request/response cycle, bjoern continues to read 0 bytes all the time, but does not close the connection. I believe this must be a bug in bjoern, however, I wonder why your browser/client does not close the connection on its end when it has nothing more to say? (Maybe it waits for a response, hm… I'll get back to this tomorrow)

**Comment by kianxineki** [comment] 2016-04-10 17:30
@jonashaag It may be that the chrome to update again requests the request without closing the connection properly.

**Comment by bulletmark** [comment] 2016-04-10 22:10
FYI, I'm subscribed to this bug because I first experienced it with bjoern 3 years ago. Every now and then my bottle app would "latch" to high/100% cpu but otherwise respond to requests ok.  I switched to meinheld where I never see the bug. As an academic exercise I switched back to updated bjoern versions a few times over the years but the bug always re-appeared within days. Never happens with meinheld. My  app gets used daily by myself and my wife using Android phone browser and chrome on PC+laptop. Here is a link to an old post by me referencing this issue https://groups.google.com/d/msg/bottlepy/wbgfiLKdoLg/RdjfCY407pwJ.

**Comment by jonashaag** [comment] 2016-04-11 09:43
I believe to have found the issue. I'd be glad if you could give it a shot.

**Closed** 2016-04-11 09:43 UTC

**Comment by kianxineki** [comment] 2016-04-11 10:14
I am testing the new version, it seems that everything works perfect! great job!

It will publish a new version pypi? to compile bjoern on all servers or wait for update: P

**Comment by bulletmark** [comment] 2016-04-11 12:19
I was intending to test this but have discovered that bjoern does not support python 3 which I moved to last year after all my pre-requisite PyPI packages had been ported, including meinheld. :(

**Comment by jonashaag** [comment] 2016-04-11 20:49
Release done!
